# Generated by Django 5.1.3 on 2024-11-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_student_email_staff_phone_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.staff'),
        ),
    ]
